server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#    对应mysql8.+版本，一定要加上时区和driverClassName
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  rabbitmq:
    port: 5672
    host: 192.168.29.128
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE #设置交换机名称，发送信息时不需要再指定交换机，默认配置的交换机
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
mybatis:
  type-aliases-package: com.leyou.item.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl