server:
  port: 10001 #tim占用端口8004
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-nodes: 192.168.29.128:9300
      cluster-name: elasticsearch
  jackson:
    default-property-inclusion: non_null #jackson响应json数据时忽略为null的字段
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5