
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
mybatis:
  type-aliases-package: cn.itcast.service.pojo
server:
  port: 10001
