server:
  port: 10006
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.29.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15