server:
  port: 10002
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    #    对应mysql8.+版本，一定要加上时区和driverClassName
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.user.pojo